### Import Libraries (Exercise 3: Training a Classification Model)

In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import math

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

pd.set_option("display.max_rows", 400)

### Load data and explore

In [2]:
df = pd.read_csv("lab4q2.csv")

In [3]:
df.head()

Date        Day  Sales  Temperature    Flyers  rainfall_log_value  \
0  1/1/2017     Sunday     10    -2.085514 -1.921262            0.866486   
1  2/1/2017     Monday     13    -1.968042 -1.921262            0.622386   
2  3/1/2017    Tuesday     15    -1.621808 -1.009448            0.622386   
3  4/1/2017  Wednesday     17    -1.028266 -0.933464            0.480947   
4  5/1/2017   Thursday     18    -1.133372 -0.553542            0.451754   

   Price  Profitable  
0      0           0  
1      0           0  
2      0           0  
3      0           0  
4      0           0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 8 columns):
Date                  365 non-null object
Day                   365 non-null object
Sales                 365 non-null int64
Temperature           365 non-null float64
Flyers                365 non-null float64
rainfall_log_value    365 non-null float64
Price                 365 non-null int64
Profitable            365 non-null int64
dtypes: float64(3), int64(3), object(2)
memory usage: 22.9+ KB


In [5]:
df["Profitable"].value_counts()

0    189
1    176
Name: Profitable, dtype: int64

### Transform data for training

In [6]:
#Drop Date and Day columns
df = df.drop(["Date"],axis=1)

In [7]:
df

Day  Sales  Temperature    Flyers  rainfall_log_value  Price  \
0       Sunday     10    -2.085514 -1.921262            0.866486      0   
1       Monday     13    -1.968042 -1.921262            0.622386      0   
2      Tuesday     15    -1.621808 -1.009448            0.622386      0   
3    Wednesday     17    -1.028266 -0.933464            0.480947      0   
4     Thursday     18    -1.133372 -0.553542            0.451754      0   
..         ...    ...          ...       ...                 ...    ...   
360  Wednesday     19    -1.114824 -0.553542            0.451754      0   
361   Thursday     16    -1.417778 -0.629526            0.585268      0   
362     Friday     15    -1.312672 -1.769293            0.585268      0   
363   Saturday     13    -1.844387 -1.389371            0.665762      0   
364     Sunday      7    -2.821260 -2.377169            1.000000      0   

     Profitable  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
360           0  
361           0  
362           0  
363           0  
364           0  

[365 rows x 7 columns]

In [8]:
X_cat = df["Day"]

In [9]:
X_cat.head()

0       Sunday
1       Monday
2      Tuesday
3    Wednesday
4     Thursday
Name: Day, dtype: object

In [10]:
X_cat

0         Sunday
1         Monday
2        Tuesday
3      Wednesday
4       Thursday
         ...    
360    Wednesday
361     Thursday
362       Friday
363     Saturday
364       Sunday
Name: Day, Length: 365, dtype: object

In [11]:
# Label encoding for Day feature
le = LabelEncoder()

In [12]:
le.fit_transform(X_cat)

array([3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3,
       1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1,
       5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5,
       6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6,
       4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4,
       0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0,
       2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2,
       3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3,
       1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1,
       5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5,
       6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6,
       4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4,
       0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0,
       2, 3, 1, 5, 6, 4, 0, 2, 3, 1, 5, 6, 4, 0, 2,

In [13]:
le.classes_

array(['Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday',
       'Wednesday'], dtype=object)

In [14]:
X_encoded = le.fit_transform(X_cat)

In [16]:
X_encoded = pd.DataFrame(X_encoded)

In [17]:
X_encoded

0
0    3
1    1
2    5
3    6
4    4
..  ..
360  6
361  4
362  0
363  2
364  3

[365 rows x 1 columns]

In [18]:
df2 = pd.concat([df,X_encoded],axis=1)

In [22]:
df2

Day  Sales  Temperature    Flyers  rainfall_log_value  Price  \
0       Sunday     10    -2.085514 -1.921262            0.866486      0   
1       Monday     13    -1.968042 -1.921262            0.622386      0   
2      Tuesday     15    -1.621808 -1.009448            0.622386      0   
3    Wednesday     17    -1.028266 -0.933464            0.480947      0   
4     Thursday     18    -1.133372 -0.553542            0.451754      0   
5       Friday     11    -2.190620 -1.313386            0.710103      0   
6     Saturday     13    -1.720732 -1.617324            0.710103      0   
7       Sunday     15    -1.436326 -0.933464            0.550787      0   
8       Monday     17    -1.399230 -1.541340            0.550787      0   
9      Tuesday     18    -1.071545 -0.553542            0.480947      0   
10   Wednesday     12    -1.739280 -1.313386            0.710103      0   
11    Thursday     14    -1.393047 -1.845277            0.622386      0   
12      Friday     15    -1.436326 -1.617324            0.622386      0   
13    Saturday     17    -1.028266 -1.313386            0.480947      0   
14      Sunday     18    -1.071545 -0.553542            0.514196      0   
15      Monday     12    -1.862935 -1.237402            0.758593      0   
16     Tuesday     14    -1.764011 -1.085433            0.665762      0   
17   Wednesday     16    -1.108641 -0.553542            0.550787      0   
18    Thursday     17    -1.090093 -0.781495            0.550787      0   
19      Friday     12    -1.801108 -1.541340            0.665762      0   
20    Saturday     14    -1.516702 -1.845277            0.585268      0   
21      Sunday     16    -1.232296 -1.617324            0.514196      0   
22      Monday     17    -1.399230 -1.465355            0.480947      0   
23     Tuesday     12    -1.986590 -1.541340            0.710103      0   
24   Wednesday     14    -1.764011 -1.237402            0.585268      0   
25    Thursday     16    -1.541433 -1.693309            0.585268      0   
26      Friday     17    -1.151920 -1.389371            0.480947      0   
27    Saturday     13    -1.597077 -1.921262            0.622386      0   
28      Sunday     14    -1.578529 -1.009448            0.622386      0   
29      Monday     17    -1.213748 -1.541340            0.480947      0   
30     Tuesday     18    -1.257027 -0.249604            0.480947      0   
31   Wednesday     18    -1.133372 -0.401573            0.451754      0   
32    Thursday     20    -0.539829 -1.389371            0.451754      0   
33      Friday     21    -0.644936 -1.161417            0.368429      0   
34    Saturday     22    -0.255423  0.434256            0.340267      0   
35      Sunday     18    -0.947890 -0.629526            0.514196      0   
36      Monday     20    -0.972621 -0.933464            0.421064      0   
37     Tuesday     21    -0.521281 -0.097635            0.368429      0   
38   Wednesday     22    -0.502733 -0.705511            0.368429      0   
39    Thursday     19    -1.114824 -0.097635            0.451754      0   
40      Friday     20    -0.663484 -0.021650            0.395325      0   
41    Saturday     21    -0.583108 -0.401573            0.395325      0   
42      Sunday     22    -0.317251  0.054334            0.340267      0   
43      Monday     18    -0.886063 -0.477557            0.514196      0   
44     Tuesday     19    -0.805687 -0.401573            0.421064      0   
45   Wednesday     20    -0.539829 -0.553542            0.395325      0   
46    Thursday     21    -0.830418 -0.705511            0.368429      0   
47      Friday     18    -1.257027 -0.857479            0.451754      0   
48    Saturday     19    -1.052997 -1.161417            0.421064      0   
49      Sunday     20    -0.663484 -0.933464            0.421064      0   
50      Monday     21    -0.644936 -1.161417            0.421064      0   
51     Tuesday     18    -1.133372 -0.933464            0.451754      0   
52   Wednesday     19    -0.805687 -

In [23]:
df2 = df2.drop("Day",axis=1)

In [24]:
df2.head()

Sales  Temperature    Flyers  rainfall_log_value  Price  Profitable  0
0     10    -2.085514 -1.921262            0.866486      0           0  3
1     13    -1.968042 -1.921262            0.622386      0           0  1
2     15    -1.621808 -1.009448            0.622386      0           0  5
3     17    -1.028266 -0.933464            0.480947      0           0  6
4     18    -1.133372 -0.553542            0.451754      0           0  4

In [30]:
df2.rename(columns={0: "Day"},inplace=True)

In [31]:
df2.head()

Sales  Temperature    Flyers  rainfall_log_value  Price  Profitable  Day
0     10    -2.085514 -1.921262            0.866486      0           0    3
1     13    -1.968042 -1.921262            0.622386      0           0    1
2     15    -1.621808 -1.009448            0.622386      0           0    5
3     17    -1.028266 -0.933464            0.480947      0           0    6
4     18    -1.133372 -0.553542            0.451754      0           0    4

In [32]:
df2.shape

(365, 7)

In [34]:
#Rearrange columns
df2 = df2[['Sales', 'Temperature', 'Flyers', 'rainfall_log_value', 'Price','Day','Profitable']]

In [35]:
df2.head()

Sales  Temperature    Flyers  rainfall_log_value  Price  Day  Profitable
0     10    -2.085514 -1.921262            0.866486      0    3           0
1     13    -1.968042 -1.921262            0.622386      0    1           0
2     15    -1.621808 -1.009448            0.622386      0    5           0
3     17    -1.028266 -0.933464            0.480947      0    6           0
4     18    -1.133372 -0.553542            0.451754      0    4           0

In [36]:
X = df2.iloc[:,0:6]
y = df2.iloc[:,6]

In [38]:
X.head()

Sales  Temperature    Flyers  rainfall_log_value  Price  Day
0     10    -2.085514 -1.921262            0.866486      0    3
1     13    -1.968042 -1.921262            0.622386      0    1
2     15    -1.621808 -1.009448            0.622386      0    5
3     17    -1.028266 -0.933464            0.480947      0    6
4     18    -1.133372 -0.553542            0.451754      0    4

In [39]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Profitable, dtype: int64

In [40]:
X.values, y.values

(array([[10.        , -2.08551378, -1.92126193,  0.86648611,  0.        ,
          3.        ],
        [13.        , -1.96804175, -1.92126193,  0.62238571,  0.        ,
          1.        ],
        [15.        , -1.62180842, -1.00944838,  0.62238571,  0.        ,
          5.        ],
        ...,
        [15.        , -1.31267152, -1.769293  ,  0.58526796,  0.        ,
          0.        ],
        [13.        , -1.84438699, -1.38937069,  0.66576208,  0.        ,
          2.        ],
        [ 7.        , -2.82125961, -2.3771687 ,  1.        ,  0.        ,
          3.        ]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
        1, 0, 1, 1, 1, 0, 0, 1, 1

### Model Training

In [41]:
#Split for training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, shuffle=True)

In [42]:
X_train.shape, X_test.shape

((255, 6), (110, 6))

In [43]:
model = LogisticRegression()

In [44]:
model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [45]:
y_predict = model.predict(X_test)

In [46]:
y_predict  #Prediction results

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1],
      dtype=int64)

In [57]:
y_test.values.reshape(-1,1)

array([[1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
    

### Model Evaluation

In [59]:
accuracy = accuracy_score(y_test,y_predict)
print('Accuracy Score is',accuracy)

Accuracy Score is 0.9545454545454546


In [61]:
cm = confusion_matrix(y_test,y_predict)
print(cm)

[[52  2]
 [ 3 53]]


In [63]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95        54
           1       0.96      0.95      0.95        56

    accuracy                           0.95       110
   macro avg       0.95      0.95      0.95       110
weighted avg       0.95      0.95      0.95       110

